// <auto-generated />
using System;
using Coursach.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coursach.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AdditionallWatch", b =>
                {
                    b.Property<Guid>("AdditionallsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WatchesId")
                        .HasColumnType("char(36)");

                    b.HasKey("AdditionallsId", "WatchesId");

                    b.HasIndex("WatchesId");

                    b.ToTable("AdditionallWatch");
                });

            modelBuilder.Entity("Coursach.Data.Additionall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Additionalls");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b373711-eb90-4beb-93f1-81b990f348d5"),
                            Name = "GPS-навигаторы"
                        },
                        new
                        {
                            Id = new Guid("69e1e9ac-ab0e-4bf7-a7a2-c719b1817029"),
                            Name = "Большая дата"
                        },
                        new
                        {
                            Id = new Guid("ef24a2a1-e467-4529-ab07-b25688c23df7"),
                            Name = "Вечный календарь"
                        },
                        new
                        {
                            Id = new Guid("ed601b75-e976-4306-a9ea-4b2ecb1aaeb9"),
                            Name = "Есть парная модель"
                        },
                        new
                        {
                            Id = new Guid("960c85cc-7ec3-460c-95e7-ae768970a65c"),
                            Name = "Карманные"
                        },
                        new
                        {
                            Id = new Guid("d69cdcbe-797d-4363-8954-74fe8b1d242b"),
                            Name = "Лимитированная серия"
                        },
                        new
                        {
                            Id = new Guid("692c12df-d684-4e92-ba29-0595688954d9"),
                            Name = "Мировое время"
                        },
                        new
                        {
                            Id = new Guid("9038a6f2-c0c3-4fa8-9910-dcbb993fddd9"),
                            Name = "Приливы-отливы"
                        },
                        new
                        {
                            Id = new Guid("78a9cadc-99e4-4b6b-b665-2c3b80d7e30c"),
                            Name = "Противоударные"
                        },
                        new
                        {
                            Id = new Guid("4da68d9b-c846-4802-b769-e745c5bc7354"),
                            Name = "Пульсометры"
                        },
                        new
                        {
                            Id = new Guid("cd84eee4-9da6-4e4d-a7cb-ea3b061e1c58"),
                            Name = "С барометром"
                        },
                        new
                        {
                            Id = new Guid("232d9bed-c5d7-4753-929c-53be17c52eb0"),
                            Name = "С будильником"
                        },
                        new
                        {
                            Id = new Guid("8842855f-f5f4-4b70-b6bc-69f706baaacb"),
                            Name = "С высотомером"
                        },
                        new
                        {
                            Id = new Guid("6a91b4ed-539f-43fa-a86c-132d79f1c4c6"),
                            Name = "Связь с мобильным телефоном"
                        },
                        new
                        {
                            Id = new Guid("1af44a1f-2d4c-43bf-8cb7-4a665e16f9a5"),
                            Name = "С глубиномером"
                        },
                        new
                        {
                            Id = new Guid("e119fc7f-0c71-4334-b87b-ca8dd92c1cbc"),
                            Name = "Сердечный ритм"
                        },
                        new
                        {
                            Id = new Guid("3845df03-a237-4a3b-89dd-be36f823242d"),
                            Name = "С измерением калорий"
                        },
                        new
                        {
                            Id = new Guid("09ea59d4-3be0-4d2a-b4bc-b0cab5af5ad4"),
                            Name = "С календарем"
                        },
                        new
                        {
                            Id = new Guid("2d990ad0-bda5-4b60-95f3-13c2d4dae5b0"),
                            Name = "Скелетоны"
                        },
                        new
                        {
                            Id = new Guid("58ed6caf-7232-4058-a4a2-a5824b5995c8"),
                            Name = "С компасом"
                        },
                        new
                        {
                            Id = new Guid("991ed83d-3ff7-43e8-ae0e-516dceb29424"),
                            Name = "С лунным календарем"
                        },
                        new
                        {
                            Id = new Guid("cc16f66c-8da3-42e8-b00e-c6f04d31eea4"),
                            Name = "С секундомером"
                        },
                        new
                        {
                            Id = new Guid("9d085e9a-6daf-4afe-b9e3-5c81117e8a63"),
                            Name = "С термометром"
                        },
                        new
                        {
                            Id = new Guid("76328ced-f420-47a4-9ca0-fe5fbbede3e0"),
                            Name = "Хронографы"
                        },
                        new
                        {
                            Id = new Guid("1e33e05f-dbd5-4b4f-9a79-7934adcbf057"),
                            Name = "Хронометры"
                        },
                        new
                        {
                            Id = new Guid("a83e4a87-413b-490c-937f-36bc4e9f7332"),
                            Name = "Шагомер"
                        });
                });

            modelBuilder.Entity("Coursach.Data.Backlight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Backlights");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8735cf0-249d-43fd-b015-f3b6e722299f"),
                            Name = "Люминесцентная"
                        },
                        new
                        {
                            Id = new Guid("6210bd6a-1b01-4178-9c0a-dd934892d201"),
                            Name = "Тритиевая"
                        },
                        new
                        {
                            Id = new Guid("86f3107a-25df-40cd-ab80-df0bf225bcf4"),
                            Name = "Электрическая"
                        });
                });

            modelBuilder.Entity("Coursach.Data.Bracelet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Bracelets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3b7dde3-4255-4fe7-b29c-a413828e042d"),
                            Name = "Браслет"
                        },
                        new
                        {
                            Id = new Guid("0b7e3f22-21d8-4ffa-8316-5f744ee353bb"),
                            Name = "Резина/пластик"
                        },
                        new
                        {
                            Id = new Guid("cb84bcd7-c712-42cd-beb4-7e34f3976396"),
                            Name = "Кожа/текстиль"
                        },
                        new
                        {
                            Id = new Guid("df8ec533-6c45-49a8-917c-6e32ee7be056"),
                            Name = "Алюминиевый"
                        },
                        new
                        {
                            Id = new Guid("c3057c2c-cbf0-403e-a296-e5e8a927b277"),
                            Name = "Атласный"
                        },
                        new
                        {
                            Id = new Guid("d13e2ed2-cdbc-41a6-9f9b-6d26ed076337"),
                            Name = "Джинсовый"
                        },
                        new
                        {
                            Id = new Guid("6cea87ac-bc64-44d8-ad08-a48e10bb6073"),
                            Name = "Карбоновый"
                        },
                        new
                        {
                            Id = new Guid("a85630cd-5931-4563-9837-f9a26b47c1d2"),
                            Name = "Каучуковый"
                        },
                        new
                        {
                            Id = new Guid("3a386075-8faa-4908-9ce2-ac102318751c"),
                            Name = "Керамический"
                        },
                        new
                        {
                            Id = new Guid("c6714173-35d4-4783-a2e6-b6b3c3721490"),
                            Name = "Кожаный"
                        },
                        new
                        {
                            Id = new Guid("037622fc-71bb-475a-ba8d-657e4beb719c"),
                            Name = "Миланский"
                        },
                        new
                        {
                            Id = new Guid("1e4c6f0c-893f-46bb-910a-0b545baf9230"),
                            Name = "Нейлоновый"
                        },
                        new
                        {
                            Id = new Guid("bf95ba78-41da-4ecd-af33-d36b51164ec2"),
                            Name = "Пластиковый"
                        },
                        new
                        {
                            Id = new Guid("f1043b75-6715-4b22-9ac4-1539e42cd7b3"),
                            Name = "Полиуретановый"
                        },
                        new
                        {
                            Id = new Guid("7404b58c-ee5a-4420-9770-26d0157bb7d3"),
                            Name = "Резиновый"
                        },
                        new
                        {
                            Id = new Guid("acc1c286-cdf7-4597-b8c4-15c37642c318"),
                            Name = "Серебряный"
                        },
                        new
                        {
                            Id = new Guid("6c73b63d-472e-44e7-a5af-6a3f3786d7e3"),
                            Name = "Силиконовый"
                        },
                        new
                        {
                            Id = new Guid("08a4da26-56d2-4686-a082-db7878e52e1a"),
                            Name = "Стальной"
                        },
                        new
                        {
                            Id = new Guid("54860f49-a3f2-4b3c-b712-86969bf8cd54"),
                            Name = "Текстильный"
                        },
                        new
                        {
                            Id = new Guid("414ba004-3156-4a4a-a8d1-f93c34282dbb"),
                            Name = "Титановый"
                        },
                        new
                        {
                            Id = new Guid("ec82ddfa-0375-4225-80c5-f6a35ffb681e"),
                            Name = "Тканевый"
                        });
                });

            modelBuilder.Entity("Coursach.Data.BraceletColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BraceletColors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b93d413f-4fc0-4dd8-a778-69d1fe3fe275"),
                            Name = "Бежевый"
                        },
                        new
                        {
                            Id = new Guid("87af60fe-1dc7-49ba-bccc-d2c201882f82"),
                            Name = "Белый"
                        },
                        new
                        {
                            Id = new Guid("e9b60471-95ea-4c4f-afe0-0770a3525924"),
                            Name = "Голубой"
                        },
                        new
                        {
                            Id = new Guid("92169422-9f15-4101-abbf-52936e9def82"),
                            Name = "Двухцветный"
                        },
                        new
                        {
                            Id = new Guid("2cabb56c-8eaf-4af1-ada7-bab50726a83b"),
                            Name = "Желтый"
                        },
                        new
                        {
                            Id = new Guid("02154ecb-4b88-4002-a87c-afdbfe12c835"),
                            Name = "Зеленый"
                        },
                        new
                        {
                            Id = new Guid("19622a60-fff5-4abb-b083-590d3d8aca12"),
                            Name = "Коричневый"
                        },
                        new
                        {
                            Id = new Guid("7dbc57dc-7efa-4f6c-93e2-4412d9f9c896"),
                            Name = "Красный"
                        },
                        new
                        {
                            Id = new Guid("b5396349-1d2a-467b-851b-3d5a411b5dd6"),
                            Name = "Оранжевый"
                        },
                        new
                        {
                            Id = new Guid("3d4a5fcf-1adb-40e4-b272-a0b129a9ab97"),
                            Name = "Прозрачный"
                        },
                        new
                        {
                            Id = new Guid("9777f626-8f4f-4d12-bc79-66522e839486"),
                            Name = "Разноцветные"
                        },
                        new
                        {
                            Id = new Guid("c8d7727a-c709-450b-bd6f-d3fa0d7e78af"),
                            Name = "Розовый"
                        },
                        new
                        {
                            Id = new Guid("b11c5ac2-b105-463f-b415-c1f29962743c"),
                            Name = "Серый"
                        },
                        new
                        {
                            Id = new Guid("f8ca1883-f3cf-4ee3-b3d5-a94447e8b5f9"),
                            Name = "Синий"
                        },
                        new
                        {
                            Id = new Guid("22562f38-d8f5-4894-a614-d4ad3c33cb2e"),
                            Name = "Фиолетовый"
                        },
                        new
                        {
                            Id = new Guid("59a54385-6c17-499e-9388-95e53b29e506"),
                            Name = "Черный"
                        });
                });

            modelBuilder.Entity("Coursach.Data.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a11455c1-4e8d-49d7-981c-f6d4dadfea49"),
                            Name = "6МХ"
                        },
                        new
                        {
                            Id = new Guid("3fbf5e0d-2b88-4f31-897c-6410e30032ef"),
                            Name = "Adriatica"
                        },
                        new
                        {
                            Id = new Guid("5d035a10-3874-48f6-96e4-9507762a1532"),
                            Name = "AGELOCER"
                        },
                        new
                        {
                            Id = new Guid("b8beb783-c0cb-4fe2-843e-00db8669825e"),
                            Name = "Alexander Shorokhoff"
                        },
                        new
                        {
                            Id = new Guid("7c8e81b0-8df3-4eb7-88ac-e168d8c77f56"),
                            Name = "Anne Klein"
                        },
                        new
                        {
                            Id = new Guid("c3d730c1-b163-4e93-a64e-1ae5f6a6612c"),
                            Name = "Armand Nicolet"
                        },
                        new
                        {
                            Id = new Guid("15477b61-4a67-497e-b861-3c8b8da07408"),
                            Name = "Armani Exchange"
                        },
                        new
                        {
                            Id = new Guid("d7f3c100-d752-4301-82ec-66289b2d2a38"),
                            Name = "Aviator"
                        },
                        new
                        {
                            Id = new Guid("9663c31b-d637-476f-81ad-505386a4dfa4"),
                            Name = "BALL"
                        },
                        new
                        {
                            Id = new Guid("598530ed-47fc-4c27-933f-df95fbc36611"),
                            Name = "Balmain"
                        },
                        new
                        {
                            Id = new Guid("fd76b7f8-9e31-4a1f-a484-4f8d7ea7bea1"),
                            Name = "Bauhaus"
                        },
                        new
                        {
                            Id = new Guid("5af06b39-d1ba-4e5a-85a2-f408d617c58d"),
                            Name = "Boccia Titanium"
                        },
                        new
                        {
                            Id = new Guid("d1c5b624-fc54-4520-b1a9-d43bd6a66560"),
                            Name = "Bomberg"
                        },
                        new
                        {
                            Id = new Guid("620b4580-56f1-48fe-b8a9-b621df14535f"),
                            Name = "Breitling"
                        },
                        new
                        {
                            Id = new Guid("4dbc2dea-3f6b-4607-bdc7-6d52970bc0f4"),
                            Name = "Briller"
                        },
                        new
                        {
                            Id = new Guid("d839ac61-c47b-4e9d-bdd3-56c442f02582"),
                            Name = "Calvin Klein"
                        },
                        new
                        {
                            Id = new Guid("d6749a6d-0e00-4505-ac46-3ba8816bb325"),
                            Name = "Candino"
                        },
                        new
                        {
                            Id = new Guid("e1a9b8d7-df7e-4144-8c13-0abf3221189b"),
                            Name = "Carl von Zeyten"
                        },
                        new
                        {
                            Id = new Guid("cafc109e-a128-4a25-9209-bfd1cf8e3fdc"),
                            Name = "Casio"
                        },
                        new
                        {
                            Id = new Guid("0a3c2fd8-34d1-42c3-bec6-3ac8f85f88f1"),
                            Name = "Caviar"
                        },
                        new
                        {
                            Id = new Guid("e3609c9d-602b-428e-b88a-2e43b4395e19"),
                            Name = "Certina"
                        },
                        new
                        {
                            Id = new Guid("c7d5eaa6-aea3-45d7-a27d-5a1b4ee005b3"),
                            Name = "CIGA Design"
                        },
                        new
                        {
                            Id = new Guid("f83bf5eb-c547-4698-b342-b67ebe6b0557"),
                            Name = "Citizen"
                        },
                        new
                        {
                            Id = new Guid("3c030fdc-1656-47c5-9a06-acdcb02f8ea1"),
                            Name = "COACH"
                        },
                        new
                        {
                            Id = new Guid("a4f2348e-d3a6-417a-89c3-c2fd5352ea26"),
                            Name = "Continental"
                        },
                        new
                        {
                            Id = new Guid("acb5e4f4-97cd-49d9-af90-1ac7ce9de143"),
                            Name = "Cornavin"
                        },
                        new
                        {
                            Id = new Guid("e1989740-892a-47a5-9013-a0cf53ec0b1d"),
                            Name = "Corum"
                        },
                        new
                        {
                            Id = new Guid("eaa22f37-9fc2-4845-8ed5-962397e3924d"),
                            Name = "Cuervo y Sobrinos"
                        },
                        new
                        {
                            Id = new Guid("3f1684c6-5912-45b6-8149-cffc996b39ee"),
                            Name = "CVSTOS"
                        },
                        new
                        {
                            Id = new Guid("4ee9639b-355b-427e-8722-fe7f41c6127b"),
                            Name = "D1 Milano"
                        },
                        new
                        {
                            Id = new Guid("54d5ae48-b6b9-4ad0-ad44-16ffc6f13314"),
                            Name = "Daniel Klein"
                        },
                        new
                        {
                            Id = new Guid("919c7921-a856-4086-a177-17581f8346d5"),
                            Name = "Daniel Wellington"
                        },
                        new
                        {
                            Id = new Guid("b40e0605-5fa3-4d55-9c68-56d328596cc9"),
                            Name = "DAVOSA"
                        },
                        new
                        {
                            Id = new Guid("94441187-c720-43d9-b93a-837d909abc15"),
                            Name = "Delbana"
                        },
                        new
                        {
                            Id = new Guid("971034fc-c1e6-4793-8589-76d4ff86e64a"),
                            Name = "Delma"
                        },
                        new
                        {
                            Id = new Guid("39e22a47-e30a-4b35-9289-a8e39361a55e"),
                            Name = "Diesel"
                        },
                        new
                        {
                            Id = new Guid("4eb49b7b-9cef-4254-a0ca-bf2b478c1455"),
                            Name = "DKNY"
                        },
                        new
                        {
                            Id = new Guid("843770d0-ae69-4836-ae18-7556e79d497a"),
                            Name = "Doodle"
                        },
                        new
                        {
                            Id = new Guid("95ccb13e-51db-4b5b-b5aa-2464bc32ec23"),
                            Name = "Ducati"
                        },
                        new
                        {
                            Id = new Guid("022c2a79-832f-45f0-b197-c7e58aef3d62"),
                            Name = "Elysee"
                        },
                        new
                        {
                            Id = new Guid("09b290be-39f9-4428-80ab-e4ffc8e9cd18"),
                            Name = "Emporio Armani"
                        },
                        new
                        {
                            Id = new Guid("970e93dd-4343-44a8-9349-2f01629be0cd"),
                            Name = "Epos"
                        },
                        new
                        {
                            Id = new Guid("46bd4c84-2911-49d8-9fe7-837017765805"),
                            Name = "Festina"
                        },
                        new
                        {
                            Id = new Guid("1c11ce64-5eca-4b25-b8a0-21ef5bb50b10"),
                            Name = "Fossil"
                        },
                        new
                        {
                            Id = new Guid("2fc091a3-5325-453f-9d9e-db491a3add8f"),
                            Name = "Frederique Constant"
                        },
                        new
                        {
                            Id = new Guid("2216fbc5-1633-48ab-a01c-173ebaad3688"),
                            Name = "Freelook"
                        },
                        new
                        {
                            Id = new Guid("bd318db2-5bca-403b-ae2c-847df9ed6e57"),
                            Name = "Furla"
                        },
                        new
                        {
                            Id = new Guid("7ea72226-7054-4dff-928a-431fdab74d8e"),
                            Name = "Garmin"
                        },
                        new
                        {
                            Id = new Guid("eab1d80c-0e91-46ed-8a59-0634e9ea2c8c"),
                            Name = "Graham"
                        },
                        new
                        {
                            Id = new Guid("fb390df2-dc06-48e7-8709-701354fdf453"),
                            Name = "Grand Seiko"
                        },
                        new
                        {
                            Id = new Guid("37eafcaf-3189-43bf-bca7-3f0468c26960"),
                            Name = "Gucci"
                        },
                        new
                        {
                            Id = new Guid("f79cb804-9132-4d98-bf18-5ba4690be5cf"),
                            Name = "Guess"
                        },
                        new
                        {
                            Id = new Guid("f8436e86-e6d1-47c9-9801-ccbbc45eb735"),
                            Name = "Guess Originals"
                        },
                        new
                        {
                            Id = new Guid("770a66bf-9a87-49a7-af70-f9bf3347e669"),
                            Name = "Hamilton"
                        },
                        new
                        {
                            Id = new Guid("de631b24-fb3d-4c6b-978f-d1131ffdc812"),
                            Name = "HEAD"
                        },
                        new
                        {
                            Id = new Guid("2fa3180a-1d23-42af-b13d-eb5e2089bb1b"),
                            Name = "HUBLOT"
                        },
                        new
                        {
                            Id = new Guid("858cee13-df35-426a-9d51-3029eec4d210"),
                            Name = "HUGO"
                        },
                        new
                        {
                            Id = new Guid("cd3b79c3-0e4c-4c34-b08d-39960067db22"),
                            Name = "Hugo Boss"
                        },
                        new
                        {
                            Id = new Guid("b843f1a9-50b6-47da-a087-d0b82982f23a"),
                            Name = "Ikepod"
                        },
                        new
                        {
                            Id = new Guid("381193cb-d65f-48e8-907d-c72f4937c167"),
                            Name = "Infantry"
                        },
                        new
                        {
                            Id = new Guid("39074783-8261-4345-86d1-56800c7e696c"),
                            Name = "Invicta"
                        },
                        new
                        {
                            Id = new Guid("bf6cb674-d63e-4f60-9081-ac9dd84c7450"),
                            Name = "Iron Annie"
                        },
                        new
                        {
                            Id = new Guid("9f08a518-f4b7-4ab7-a260-837445a2a238"),
                            Name = "Jacques Lemans"
                        },
                        new
                        {
                            Id = new Guid("a9f95b91-d7cd-4631-ae8f-25d0c6a5f154"),
                            Name = "Juicy Couture"
                        },
                        new
                        {
                            Id = new Guid("f9159071-9201-435e-b8b8-fee8f777448e"),
                            Name = "Just Cavalli"
                        },
                        new
                        {
                            Id = new Guid("dfaa8612-d277-4b50-ab1a-a15eef53598f"),
                            Name = "Korloff"
                        },
                        new
                        {
                            Id = new Guid("5320a73c-20db-44a4-8837-feacd7b751b0"),
                            Name = "Lacoste"
                        },
                        new
                        {
                            Id = new Guid("790fd10f-890e-4165-b4ed-9c929cb0dfea"),
                            Name = "L Duchen"
                        },
                        new
                        {
                            Id = new Guid("71f57d49-79f7-40b5-9585-4f76dd6258fc"),
                            Name = "Lee Cooper"
                        },
                        new
                        {
                            Id = new Guid("720029a8-b506-4925-ad4a-d70bdc45c2b6"),
                            Name = "LIU JO"
                        },
                        new
                        {
                            Id = new Guid("ec108c01-35ce-473a-adbd-9880309e88f6"),
                            Name = "Locman"
                        },
                        new
                        {
                            Id = new Guid("0e0a08b3-9e02-4506-8a5a-054bdadad1b2"),
                            Name = "Longines"
                        },
                        new
                        {
                            Id = new Guid("2991fe97-bb39-4e92-ba4c-1d5c9e227497"),
                            Name = "Louis XVI"
                        },
                        new
                        {
                            Id = new Guid("c0f81b7e-ce3f-4b3c-a9e4-245dc7cbe8cd"),
                            Name = "Luminox"
                        },
                        new
                        {
                            Id = new Guid("d3583ef5-814b-4ebf-9fc8-3541036a90c8"),
                            Name = "M2Z"
                        },
                        new
                        {
                            Id = new Guid("552fab6b-3a83-4b4c-89c6-b2f0f83eb2de"),
                            Name = "Mathey-Tissot"
                        },
                        new
                        {
                            Id = new Guid("5690032d-0f9c-49b9-8266-bbd266d1a22d"),
                            Name = "Maurice Lacroix"
                        },
                        new
                        {
                            Id = new Guid("e68f9688-bcea-4972-b782-1e70c600616b"),
                            Name = "Mazzucato"
                        },
                        new
                        {
                            Id = new Guid("b5719415-2b49-40f2-8761-9a7ec442898f"),
                            Name = "Michael Kors"
                        },
                        new
                        {
                            Id = new Guid("72b5d02b-9015-4ad7-84c8-f971d8963130"),
                            Name = "Microwear"
                        },
                        new
                        {
                            Id = new Guid("6ba40d86-7def-4429-aafc-5b188ebf9c53"),
                            Name = "Mido"
                        },
                        new
                        {
                            Id = new Guid("dfedf668-d442-47ec-88c9-6c1bb89fd99a"),
                            Name = "Mondaine"
                        },
                        new
                        {
                            Id = new Guid("b69db020-37d2-4c86-b7a7-9e5d62f0647d"),
                            Name = "MVMT"
                        },
                        new
                        {
                            Id = new Guid("00e9bb7d-e23b-4aa4-b01b-175e76fafa39"),
                            Name = "Nautica"
                        },
                        new
                        {
                            Id = new Guid("d5253452-2fca-4023-a8c3-0561b5001637"),
                            Name = "NIKA"
                        },
                        new
                        {
                            Id = new Guid("3618b8a7-b972-4e63-895b-adba6f90dbe9"),
                            Name = "NORQAIN"
                        },
                        new
                        {
                            Id = new Guid("5aca5967-67fb-437f-8662-ad38ee885316"),
                            Name = "Obaku"
                        },
                        new
                        {
                            Id = new Guid("6c283026-4755-4878-948d-dcb5e96df6fe"),
                            Name = "Olivia Burton"
                        },
                        new
                        {
                            Id = new Guid("9e57e508-a538-4391-81f8-40d915b568b9"),
                            Name = "Orient"
                        },
                        new
                        {
                            Id = new Guid("5cc49c9a-ed35-4ead-a0fe-ab1d76460207"),
                            Name = "Orient Star"
                        },
                        new
                        {
                            Id = new Guid("73d83462-bd50-4235-b0a1-18e6e4ad4841"),
                            Name = "Perrelet"
                        },
                        new
                        {
                            Id = new Guid("56118fef-d066-4f65-b2b1-d736adc8fee4"),
                            Name = "Philipp Plein"
                        },
                        new
                        {
                            Id = new Guid("2cb3adaa-3b3b-497e-abc9-fcb4b32f8117"),
                            Name = "Pierre Ricaud"
                        },
                        new
                        {
                            Id = new Guid("7daf3a97-4117-453d-9c4c-e86ac0abd69a"),
                            Name = "PLEIN SPORT"
                        },
                        new
                        {
                            Id = new Guid("c7f53d50-fa41-4c17-8920-7027611f152f"),
                            Name = "Poljot"
                        },
                        new
                        {
                            Id = new Guid("21cbd939-c689-4b4a-ab80-2d1324dc20ff"),
                            Name = "Rado"
                        },
                        new
                        {
                            Id = new Guid("724bad9c-11eb-4284-b436-3ac73b333814"),
                            Name = "Raymond Weil"
                        },
                        new
                        {
                            Id = new Guid("0feeebfd-bb8e-4402-aafb-f008dfc2ec58"),
                            Name = "Rodania"
                        },
                        new
                        {
                            Id = new Guid("2f3e587b-2649-450f-9aab-528d82dd996b"),
                            Name = "Rotary"
                        },
                        new
                        {
                            Id = new Guid("0b6ce130-4e23-450f-ba76-d4ada116e3c0"),
                            Name = "SAGA"
                        },
                        new
                        {
                            Id = new Guid("4991a14a-4e7d-4948-9e3a-ad40cc2279b8"),
                            Name = "Salvatore Ferragamo"
                        },
                        new
                        {
                            Id = new Guid("5c0647be-7606-4595-9a6b-db8bc9efda66"),
                            Name = "Santa Barbara Polo &amp; Racquet Club"
                        },
                        new
                        {
                            Id = new Guid("917d856a-fe8e-4455-a300-72da7de2b362"),
                            Name = "Sector"
                        },
                        new
                        {
                            Id = new Guid("b34abb86-02e5-4a21-acf1-c395a86cb074"),
                            Name = "Seiko"
                        },
                        new
                        {
                            Id = new Guid("8a4d1c7b-c2b0-449a-abfa-3b117ffbfb97"),
                            Name = "Sergio Tacchini"
                        },
                        new
                        {
                            Id = new Guid("9348c534-e6bf-4ace-9cfe-70be570b6bac"),
                            Name = "Silvana"
                        },
                        new
                        {
                            Id = new Guid("1910903b-015a-4c2c-9c89-ee1c8805379f"),
                            Name = "Skagen"
                        },
                        new
                        {
                            Id = new Guid("b8303bb8-25e0-4110-8179-d05e1563d1c9"),
                            Name = "SOKOLOV"
                        },
                        new
                        {
                            Id = new Guid("c422e826-870e-4475-ae13-d6c15eb404a6"),
                            Name = "Stuhrling"
                        },
                        new
                        {
                            Id = new Guid("b34bd48e-d1b0-4afc-8487-02e733627cf7"),
                            Name = "Suunto"
                        },
                        new
                        {
                            Id = new Guid("370a1b8e-9fa1-439d-a148-d511879fc787"),
                            Name = "Swarovski"
                        },
                        new
                        {
                            Id = new Guid("8f74917f-e5ba-45a8-b0c9-05dc3b5ce6b2"),
                            Name = "Swatch"
                        },
                        new
                        {
                            Id = new Guid("d51213ea-c69b-428e-8a44-7c049edccb99"),
                            Name = "Swiss Military Hanowa"
                        },
                        new
                        {
                            Id = new Guid("18e80a3b-a078-48a3-b234-eb35889cc91c"),
                            Name = "TAG Heuer"
                        },
                        new
                        {
                            Id = new Guid("34a46f19-b5df-4b09-9e1d-c55bb4b3b3e4"),
                            Name = "TechnoMarine"
                        },
                        new
                        {
                            Id = new Guid("d0e2a987-12ad-4d46-a165-05a6f4aeae70"),
                            Name = "The Electricianz"
                        },
                        new
                        {
                            Id = new Guid("eb7c4ba7-331f-4eda-989e-53790afd07b3"),
                            Name = "Thomas Sabo"
                        },
                        new
                        {
                            Id = new Guid("ccd67fb4-9d6b-4a84-ae2a-5517903e2ed7"),
                            Name = "Timberland"
                        },
                        new
                        {
                            Id = new Guid("a745e485-242c-4230-bd83-c6102dab9e23"),
                            Name = "Timex"
                        },
                        new
                        {
                            Id = new Guid("512c974d-b5a7-41c4-8964-ae3adcda9709"),
                            Name = "Tissot"
                        },
                        new
                        {
                            Id = new Guid("09c93776-a50e-4acb-830e-1d03c7abfe81"),
                            Name = "Titoni"
                        },
                        new
                        {
                            Id = new Guid("5bfaa9a1-9cf4-42b1-bda5-33c587501b1d"),
                            Name = "Tommy Hilfiger"
                        },
                        new
                        {
                            Id = new Guid("57d5b468-72c9-4408-87ee-8d602b8ebde2"),
                            Name = "TOUS"
                        },
                        new
                        {
                            Id = new Guid("2240bbc8-5164-43ad-93ab-e7da9ec20387"),
                            Name = "Traser"
                        },
                        new
                        {
                            Id = new Guid("5397f264-ca56-4d21-927e-94f2cf402aa0"),
                            Name = "Tsar Bomba"
                        },
                        new
                        {
                            Id = new Guid("706d951d-c6f2-4b22-bc6f-6dd6dc60a1ce"),
                            Name = "TSEDRO"
                        },
                        new
                        {
                            Id = new Guid("53f01fa2-fa41-4d19-8dd2-255de03ea089"),
                            Name = "Venezianico"
                        },
                        new
                        {
                            Id = new Guid("d4873979-725e-4419-b8d6-d60b6339e122"),
                            Name = "Versace"
                        },
                        new
                        {
                            Id = new Guid("7593afb9-d7b3-4ae2-ab56-3d11efc7fcae"),
                            Name = "VERSUS Versace"
                        },
                        new
                        {
                            Id = new Guid("43e61397-ce33-419a-a402-e19f58cea649"),
                            Name = "Victorinox"
                        },
                        new
                        {
                            Id = new Guid("d880d305-de96-40d4-ad08-eb3215e00baf"),
                            Name = "VMF"
                        },
                        new
                        {
                            Id = new Guid("77c7ad68-6365-4e4e-87b3-ddd513ca4281"),
                            Name = "Wainer"
                        },
                        new
                        {
                            Id = new Guid("de89be33-be43-4dc7-b3df-7cec53c1fe39"),
                            Name = "Wenger"
                        },
                        new
                        {
                            Id = new Guid("be720237-40ab-4574-b82b-a649a28888ea"),
                            Name = "Zeppelin"
                        },
                        new
                        {
                            Id = new Guid("5d253915-b90f-4663-98cf-b1641af67c83"),
                            Name = "Восток"
                        },
                        new
                        {
                            Id = new Guid("9a142f1d-ebb4-4509-b1a0-d98fdba4aad8"),
                            Name = "Златоустовский часовой завод"
                        },
                        new
                        {
                            Id = new Guid("53080c0f-adc1-46d4-8346-f711d6862708"),
                            Name = "Михаил Москвин"
                        },
                        new
                        {
                            Id = new Guid("af3580a9-d5a8-4a47-b75f-93b42942ffeb"),
                            Name = "Молния"
                        },
                        new
                        {
                            Id = new Guid("8309fd3a-8152-4be1-be2a-e7089340f5aa"),
                            Name = "Подарочные сертификаты"
                        },
                        new
                        {
                            Id = new Guid("7a3b9e5e-5c1b-4e72-87a9-2d7e9d7e2908"),
                            Name = "Слава"
                        },
                        new
                        {
                            Id = new Guid("4f346fa2-172d-408a-b23d-49bb1535a48f"),
                            Name = "Специальное предложение"
                        },
                        new
                        {
                            Id = new Guid("effdadcf-7853-431b-a95c-c95de85a7044"),
                            Name = "Спецназ"
                        },
                        new
                        {
                            Id = new Guid("156f4213-962b-4349-8e5c-471316d1b49e"),
                            Name = "Штурманские"
                        });
                });

            modelBuilder.Entity("Coursach.Data.CaseColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CaseColors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dfa35423-626f-4985-b458-c4ffe9db07c7"),
                            Name = "Бежевый"
                        },
                        new
                        {
                            Id = new Guid("afd5e969-3f53-4785-b63a-227cec2efd9f"),
                            Name = "Белый"
                        },
                        new
                        {
                            Id = new Guid("0764bfe1-69ae-4de4-97c4-e0e5a6dbd43f"),
                            Name = "Голубой"
                        },
                        new
                        {
                            Id = new Guid("ada979b6-ee38-438b-8bb5-f576ab91f902"),
                            Name = "Двухцветный"
                        },
                        new
                        {
                            Id = new Guid("f482244b-f9bd-4a90-9081-7e5384b10529"),
                            Name = "Желтый"
                        },
                        new
                        {
                            Id = new Guid("a20b9c1d-f82a-44af-b1a4-3f67bcea3d77"),
                            Name = "Зеленый"
                        },
                        new
                        {
                            Id = new Guid("4f736d86-1047-477c-9838-35533faa2040"),
                            Name = "Коричневый"
                        },
                        new
                        {
                            Id = new Guid("c8373f91-c09a-4a08-af22-7f782c661c83"),
                            Name = "Красный"
                        },
                        new
                        {
                            Id = new Guid("9ab3f512-a307-424b-be61-3cb8f3a6d3f4"),
                            Name = "Оранжевый"
                        },
                        new
                        {
                            Id = new Guid("6e53f786-f928-40ab-a002-318f1fc47cf6"),
                            Name = "Позолоченный"
                        },
                        new
                        {
                            Id = new Guid("12a87818-f013-4d43-8742-f9d142319c31"),
                            Name = "Прозрачный"
                        },
                        new
                        {
                            Id = new Guid("9d1254b9-78eb-478c-95c4-a6423d23fda7"),
                            Name = "Разноцветные"
                        },
                        new
                        {
                            Id = new Guid("7c761c7e-ea6c-4a5b-9558-4d8b4eb8532e"),
                            Name = "Розовый"
                        },
                        new
                        {
                            Id = new Guid("48ad5b70-8823-4cb9-8381-4adb76ee2286"),
                            Name = "Серый"
                        },
                        new
                        {
                            Id = new Guid("235d3f02-12fe-4a22-bc39-61096039dbaf"),
                            Name = "Синий"
                        },
                        new
                        {
                            Id = new Guid("6f2065f9-8ad8-4dac-815c-c8d2219c433b"),
                            Name = "Фиолетовый"
                        },
                        new
                        {
                            Id = new Guid("f057550e-b5f0-4a58-b617-432f12567a6f"),
                            Name = "Черный"
                        });
                });

            modelBuilder.Entity("Coursach.Data.CaseForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CaseForms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d727ee20-e277-4ca0-8ef7-6877090e6b30"),
                            Name = "Бочка"
                        },
                        new
                        {
                            Id = new Guid("6b98937b-f022-4107-8544-e171152d133c"),
                            Name = "Квадрат"
                        },
                        new
                        {
                            Id = new Guid("867dbda3-8cf3-4bdc-811a-74f177d520d7"),
                            Name = "Круг"
                        },
                        new
                        {
                            Id = new Guid("bf64ed74-f3f1-438e-b061-de8d55118b58"),
                            Name = "Необычный"
                        },
                        new
                        {
                            Id = new Guid("bd3e5801-a54f-46e3-93f0-c6b7334e727b"),
                            Name = "Овал"
                        },
                        new
                        {
                            Id = new Guid("a40d52f0-77e4-45ec-a394-59e1cf17d79b"),
                            Name = "Прямоугольник"
                        },
                        new
                        {
                            Id = new Guid("4ab0dc67-96b5-417e-ac14-3adef5f49b51"),
                            Name = "Треугольник"
                        });
                });

            modelBuilder.Entity("Coursach.Data.CaseMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CaseMaterials");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50291767-14ce-45b2-9fe4-b4498929e285"),
                            Name = "Металлический"
                        },
                        new
                        {
                            Id = new Guid("5e45cf74-2cf3-4704-86f6-33fbec2c0af9"),
                            Name = "Сталь"
                        },
                        new
                        {
                            Id = new Guid("7c34d765-1914-41b9-8cbb-376e68ab9a3e"),
                            Name = "Титан"
                        },
                        new
                        {
                            Id = new Guid("aac33f0a-c7e2-43a2-94a6-ab1e4a0b0041"),
                            Name = "Золото"
                        },
                        new
                        {
                            Id = new Guid("60479906-756e-4eba-99d4-af6cb25b4d2f"),
                            Name = "Желтое золото"
                        },
                        new
                        {
                            Id = new Guid("0d8791b3-ce74-4feb-bdc1-d38c5740a747"),
                            Name = "Белое золото"
                        },
                        new
                        {
                            Id = new Guid("124e456f-d10c-4bc1-b659-b1e8d6271d46"),
                            Name = "Красное золото"
                        },
                        new
                        {
                            Id = new Guid("176f20ef-d864-41f7-9df1-878c8828caf0"),
                            Name = "Розовое золото"
                        },
                        new
                        {
                            Id = new Guid("1a95a3f9-8c1b-4aff-999c-0cb35f23ba1c"),
                            Name = "Серебро"
                        },
                        new
                        {
                            Id = new Guid("6f8be7a0-cf14-4952-8ea4-f829c78518e1"),
                            Name = "Алюминий"
                        },
                        new
                        {
                            Id = new Guid("4a74034c-ea07-4a16-8a01-05721885f112"),
                            Name = "Бронза"
                        },
                        new
                        {
                            Id = new Guid("ef2a16ac-6ed4-4f75-adc1-957e9055a5ed"),
                            Name = "Карбон"
                        },
                        new
                        {
                            Id = new Guid("0f94d265-2c4d-4c2c-8826-9a30f268e974"),
                            Name = "Каучук"
                        },
                        new
                        {
                            Id = new Guid("77b4c398-fdd5-40cf-b59a-c310cd5c4051"),
                            Name = "Керамический"
                        },
                        new
                        {
                            Id = new Guid("014b2a1d-d895-40a7-9d9a-f41c42df0c9d"),
                            Name = "Пластик"
                        },
                        new
                        {
                            Id = new Guid("7d14c639-1f93-4089-95b4-d3f04e931ee9"),
                            Name = "Резина"
                        },
                        new
                        {
                            Id = new Guid("103c6169-66e9-436f-86dc-040a72950f30"),
                            Name = "Силикон"
                        });
                });

            modelBuilder.Entity("Coursach.Data.CaseSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CaseSizes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("34c1a17d-61af-4d53-b100-ff757d7c4f1d"),
                            Name = "Большие"
                        },
                        new
                        {
                            Id = new Guid("de054b7e-d0e7-4d23-90e0-847b0aaa149f"),
                            Name = "Тонкие"
                        },
                        new
                        {
                            Id = new Guid("dc730cfe-6460-496b-ad58-53796ceb1ef0"),
                            Name = "Маленькие"
                        },
                        new
                        {
                            Id = new Guid("02c8dc3f-3560-4216-838e-bdd606a9a25f"),
                            Name = "Стандартные"
                        });
                });

            modelBuilder.Entity("Coursach.Data.ClockFace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ClockFaces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9be7b985-5942-4e12-85f1-14460ab4e173"),
                            Name = "Комбинированный"
                        },
                        new
                        {
                            Id = new Guid("49eda4f3-a961-460b-976b-30ebdd931641"),
                            Name = "Стрелочный"
                        },
                        new
                        {
                            Id = new Guid("8d3fb79f-5515-42ae-bb87-df8622cd5036"),
                            Name = "Цифровой"
                        });
                });

            modelBuilder.Entity("Coursach.Data.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9866111b-19cb-4122-8bf0-7d25ad74ddb0"),
                            Name = "Швейцария"
                        },
                        new
                        {
                            Id = new Guid("3945cbd8-c7f6-478d-874d-04e7955c9e63"),
                            Name = "Япония"
                        },
                        new
                        {
                            Id = new Guid("18c9e79f-7f62-4869-9b35-ae69ad746311"),
                            Name = "Россия"
                        },
                        new
                        {
                            Id = new Guid("f2e4e903-87d8-4e8b-8414-e8b480f36920"),
                            Name = "Германия"
                        },
                        new
                        {
                            Id = new Guid("0d318fcc-0408-46c5-82d9-ad3e28c384f6"),
                            Name = "Австрия"
                        },
                        new
                        {
                            Id = new Guid("7b9eedfc-b5ea-403d-9a73-003d3c681546"),
                            Name = "Бельгия"
                        },
                        new
                        {
                            Id = new Guid("2d32f8d0-4492-42a0-84ed-6ab167c86a5f"),
                            Name = "Великобритания"
                        },
                        new
                        {
                            Id = new Guid("ee47760f-f229-4c87-9f54-75eda2d24aa2"),
                            Name = "Гонконг"
                        },
                        new
                        {
                            Id = new Guid("4045e52f-f082-4aa4-b2b1-f70f9593b148"),
                            Name = "Дания"
                        },
                        new
                        {
                            Id = new Guid("31c16712-7a39-4469-aaeb-5a76e1fd4a12"),
                            Name = "Испания"
                        },
                        new
                        {
                            Id = new Guid("1863e33d-bded-402b-8251-8dae2daf75e4"),
                            Name = "Италия"
                        },
                        new
                        {
                            Id = new Guid("2fee547d-5070-4c81-8a4d-b8d4d5106cfa"),
                            Name = "Китай"
                        },
                        new
                        {
                            Id = new Guid("e1b324d5-e946-496e-9187-84f11bf83a58"),
                            Name = "США"
                        },
                        new
                        {
                            Id = new Guid("67fb6a12-2c8c-4c5f-af6b-d16ebdd5de78"),
                            Name = "Турция"
                        },
                        new
                        {
                            Id = new Guid("64c0b3a3-844e-4cc6-85c6-5cd141e70498"),
                            Name = "Финляндия"
                        },
                        new
                        {
                            Id = new Guid("72783be3-5e78-4a3c-95e2-2bc0d8fb3548"),
                            Name = "Франция"
                        },
                        new
                        {
                            Id = new Guid("df83dc01-d929-4d74-8bf8-b5fdeb40bc41"),
                            Name = "Швеция"
                        },
                        new
                        {
                            Id = new Guid("8c581dff-c02a-4e7e-8e3f-035326ca287e"),
                            Name = "Южная Корея"
                        });
                });

            modelBuilder.Entity("Coursach.Data.Decoration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Decorations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("144f0222-c75f-4f31-afaa-a30498eabcba"),
                            Name = "Аметисты"
                        },
                        new
                        {
                            Id = new Guid("f3b81bbe-8567-4294-a6ee-96fad70fe124"),
                            Name = "Бриллианты"
                        },
                        new
                        {
                            Id = new Guid("f9dcb882-5b00-455b-b66c-625fae6255b3"),
                            Name = "Вставки из золота"
                        },
                        new
                        {
                            Id = new Guid("803d8faf-a409-4d38-bdf7-b676bb67c7aa"),
                            Name = "Вставки из пластика"
                        },
                        new
                        {
                            Id = new Guid("0b83296a-d30d-4d0e-8cdf-f5d80cd9283a"),
                            Name = "Вставки керамические"
                        },
                        new
                        {
                            Id = new Guid("2faf2950-1f39-45ac-9b40-f3cb66a36d0f"),
                            Name = "Жемчуг"
                        },
                        new
                        {
                            Id = new Guid("0ef3976e-5dd2-4256-a81d-95b0238c65ad"),
                            Name = "Кристаллы Swarovski"
                        },
                        new
                        {
                            Id = new Guid("71c0f11a-f01c-49cb-aa41-5d9d4369a2e9"),
                            Name = "Рубины"
                        },
                        new
                        {
                            Id = new Guid("00f9e8aa-5513-44b3-94fe-77f9edbe6421"),
                            Name = "Сапфиры"
                        },
                        new
                        {
                            Id = new Guid("86cce35c-7d8b-4369-be97-5da5a87bdc21"),
                            Name = "Топазы"
                        },
                        new
                        {
                            Id = new Guid("4222c063-ddc4-47bd-8854-a82d1e4993f5"),
                            Name = "Фианиты"
                        },
                        new
                        {
                            Id = new Guid("c8c6a2de-14ef-4e31-b878-919adf3833ff"),
                            Name = "Хрусталь"
                        },
                        new
                        {
                            Id = new Guid("2487911a-3586-447a-93af-9753dda23378"),
                            Name = "Цирконы"
                        },
                        new
                        {
                            Id = new Guid("10aaf1f1-ee7f-4728-8823-835c2e3117c4"),
                            Name = "Эмаль"
                        },
                        new
                        {
                            Id = new Guid("e0a8c827-36c8-4295-a6e2-f105058b55fc"),
                            Name = "Янтарь"
                        });
                });

            modelBuilder.Entity("Coursach.Data.GlassType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GlassTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("207340a6-0c87-4223-9c40-c806fd8bdf26"),
                            Name = "Минеральное"
                        },
                        new
                        {
                            Id = new Guid("187f822b-6d17-4dd2-aedb-4e84c9d10cfb"),
                            Name = "Органическое"
                        },
                        new
                        {
                            Id = new Guid("6126d885-dc07-4780-8c25-8b09f4fdb524"),
                            Name = "Сапфировое"
                        });
                });

            modelBuilder.Entity("Coursach.Data.NumberType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("NumberTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d54da21e-eafa-4140-81b0-e091acc0a10a"),
                            Name = "Арабские"
                        },
                        new
                        {
                            Id = new Guid("a75420dd-91f8-44db-8f53-cd340a270588"),
                            Name = "Без меток"
                        },
                        new
                        {
                            Id = new Guid("18a2e431-a717-452c-b98c-9f5a9aa8367e"),
                            Name = "Римские"
                        },
                        new
                        {
                            Id = new Guid("8a4ef251-333e-46de-8efa-071afd778092"),
                            Name = "Точки"
                        },
                        new
                        {
                            Id = new Guid("20a61d40-651c-4dfb-9a96-6b068e08d7fb"),
                            Name = "Штрихи"
                        });
                });

            modelBuilder.Entity("Coursach.Data.Style", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Styles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2e6a83aa-4fab-4e3f-848c-72e0b86df844"),
                            Name = "Военные"
                        },
                        new
                        {
                            Id = new Guid("365239da-e64f-46b9-a275-f0df928062bc"),
                            Name = "Дизайнерские"
                        },
                        new
                        {
                            Id = new Guid("104ff71d-da7f-4de5-ad80-05f3fe01dc3f"),
                            Name = "Милитари"
                        },
                        new
                        {
                            Id = new Guid("9f554d9e-106e-4311-b6b0-f5782515e042"),
                            Name = "На каждый день"
                        },
                        new
                        {
                            Id = new Guid("449d08d3-1afd-4ac8-b2cf-ea0a2bfba404"),
                            Name = "Пилотские"
                        },
                        new
                        {
                            Id = new Guid("e2da6523-8609-4013-853e-f57a263dc04c"),
                            Name = "Под костюм"
                        },
                        new
                        {
                            Id = new Guid("84a98ad6-195a-4791-8d15-6a425acdcfb1"),
                            Name = "Спортивные"
                        });
                });

            modelBuilder.Entity("Coursach.Data.Watch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BacklightId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BraceletColorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BraceletId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<Guid>("CaseColorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CaseFormId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CaseMaterialId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CaseSizeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClockFaceId")
                        .HasColumnType("char(36)");

                    b.Property<uint>("Count")
                        .HasColumnType("int unsigned");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<Guid>("GlassTypeId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Mechanism")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("NumberTypeId")
                        .HasColumnType("char(36)");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("StyleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WaterResistantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("BacklightId");

                    b.HasIndex("BraceletColorId");

                    b.HasIndex("BraceletId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CaseColorId");

                    b.HasIndex("CaseFormId");

                    b.HasIndex("CaseMaterialId");

                    b.HasIndex("CaseSizeId");

                    b.HasIndex("ClockFaceId");

                    b.HasIndex("CountryId");

                    b.HasIndex("GlassTypeId");

                    b.HasIndex("NumberTypeId");

                    b.HasIndex("StyleId");

                    b.HasIndex("WaterResistantId");

                    b.ToTable("Watches");
                });

            modelBuilder.Entity("Coursach.Data.WaterResistant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("WaterResistants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9bb13ddc-76ce-447a-9754-4ab9da20a6cf"),
                            Name = "От 10WR"
                        },
                        new
                        {
                            Id = new Guid("4b37d4e2-c212-4ff7-ba3c-c6f2048c2179"),
                            Name = "От 30WR"
                        },
                        new
                        {
                            Id = new Guid("da18a593-e43d-43ce-bd94-348c364f9425"),
                            Name = "От 50WR"
                        },
                        new
                        {
                            Id = new Guid("c749bca2-b4e6-4453-99bf-c69aa2478200"),
                            Name = "От 100WR"
                        },
                        new
                        {
                            Id = new Guid("5970c7c3-8971-41dc-98a3-a527831307c2"),
                            Name = "От 200WR"
                        },
                        new
                        {
                            Id = new Guid("fad395ea-8b22-4077-b00b-f9a938f8d549"),
                            Name = "От 300WR"
                        });
                });

            modelBuilder.Entity("DecorationWatch", b =>
                {
                    b.Property<Guid>("DecorationsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WatchesId")
                        .HasColumnType("char(36)");

                    b.HasKey("DecorationsId", "WatchesId");

                    b.HasIndex("WatchesId");

                    b.ToTable("DecorationWatch");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AdditionallWatch", b =>
                {
                    b.HasOne("Coursach.Data.Additionall", null)
                        .WithMany()
                        .HasForeignKey("AdditionallsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coursach.Data.Watch", null)
                        .WithMany()
                        .HasForeignKey("WatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Coursach.Data.Watch", b =>
                {
                    b.HasOne("Coursach.Data.Backlight", "Backlight")
                        .WithMany("Watches")
                        .HasForeignKey("BacklightId");

                    b.HasOne("Coursach.Data.BraceletColor", "BraceletColor")
                        .WithMany("Watches")
                        .HasForeignKey("BraceletColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coursach.Data.Bracelet", "Bracelet")
                        .WithMany("Watches")
                        .HasForeignKey("BraceletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coursach.Data.Brand", "Brand")
                        .WithMany("Watches")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coursach.Data.CaseColor", "CaseColor")
                        .WithMany("Watches")
                        .HasForeignKey("CaseColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coursach.Data.CaseForm", "CaseForm")
                        .WithMany("Watches")
                        .HasForeignKey("CaseFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coursach.Data.CaseMaterial", "CaseMaterial")
                        .WithMany("Watches")
                        .HasForeignKey("CaseMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coursach.Data.CaseSize", "CaseSize")
                        .WithMany("Watches")
                        .HasForeignKey("CaseSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coursach.Data.ClockFace", "ClockFace")
                        .WithMany("Watches")
                        .HasForeignKey("ClockFaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coursach.Data.Country", "Country")
                        .WithMany("Watches")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coursach.Data.GlassType", "GlassType")
                        .WithMany("Watches")
                        .HasForeignKey("GlassTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coursach.Data.NumberType", "NumberType")
                        .WithMany("Watches")
                        .HasForeignKey("NumberTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coursach.Data.Style", "Style")
                        .WithMany("Watches")
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coursach.Data.WaterResistant", "WaterResistant")
                        .WithMany("Watches")
                        .HasForeignKey("WaterResistantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Backlight");

                    b.Navigation("Bracelet");

                    b.Navigation("BraceletColor");

                    b.Navigation("Brand");

                    b.Navigation("CaseColor");

                    b.Navigation("CaseForm");

                    b.Navigation("CaseMaterial");

                    b.Navigation("CaseSize");

                    b.Navigation("ClockFace");

                    b.Navigation("Country");

                    b.Navigation("GlassType");

                    b.Navigation("NumberType");

                    b.Navigation("Style");

                    b.Navigation("WaterResistant");
                });

            modelBuilder.Entity("DecorationWatch", b =>
                {
                    b.HasOne("Coursach.Data.Decoration", null)
                        .WithMany()
                        .HasForeignKey("DecorationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coursach.Data.Watch", null)
                        .WithMany()
                        .HasForeignKey("WatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Coursach.Data.Backlight", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("Coursach.Data.Bracelet", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("Coursach.Data.BraceletColor", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("Coursach.Data.Brand", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("Coursach.Data.CaseColor", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("Coursach.Data.CaseForm", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("Coursach.Data.CaseMaterial", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("Coursach.Data.CaseSize", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("Coursach.Data.ClockFace", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("Coursach.Data.Country", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("Coursach.Data.GlassType", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("Coursach.Data.NumberType", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("Coursach.Data.Style", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("Coursach.Data.WaterResistant", b =>
                {
                    b.Navigation("Watches");
                });
#pragma warning restore 612, 618
        }
    }
}
